name: track_elephants
description: "A new Flutter project."

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  firebase_core: ^2.27.1
  firebase_database: ^10.4.10
  cloud_firestore: ^4.15.9
  intl: ^0.17.0
  url_launcher: ^6.0.12
  flutter_phone_direct_caller: ^2.1.1
  flutter_vlc_player: ^7.4.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/The_Common_Wanderer_-9889.jpg
